// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MwS5_E0_sbCNx-EEAiriRofKNv2PzaY',
    appId: '1:565588622444:web:db5dceb707e9f06941ec49',
    messagingSenderId: '565588622444',
    projectId: 'adot-batimento',
    authDomain: 'adot-batimento.firebaseapp.com',
    databaseURL: 'https://adot-batimento-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adot-batimento.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkptgBkg8v-GoBt3D9LeW-4cZ3vRoN5gw',
    appId: '1:565588622444:android:c9c4ab817167e7d341ec49',
    messagingSenderId: '565588622444',
    projectId: 'adot-batimento',
    databaseURL: 'https://adot-batimento-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adot-batimento.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwevrGRb9fqT4e0hmLnCVQthRShxpxroM',
    appId: '1:565588622444:ios:b4379544d1feef6441ec49',
    messagingSenderId: '565588622444',
    projectId: 'adot-batimento',
    databaseURL: 'https://adot-batimento-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adot-batimento.firebasestorage.app',
    iosBundleId: 'com.example.monitorVitais',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwevrGRb9fqT4e0hmLnCVQthRShxpxroM',
    appId: '1:565588622444:ios:b4379544d1feef6441ec49',
    messagingSenderId: '565588622444',
    projectId: 'adot-batimento',
    databaseURL: 'https://adot-batimento-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adot-batimento.firebasestorage.app',
    iosBundleId: 'com.example.monitorVitais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7MwS5_E0_sbCNx-EEAiriRofKNv2PzaY',
    appId: '1:565588622444:web:7c8ca475b17bbb8641ec49',
    messagingSenderId: '565588622444',
    projectId: 'adot-batimento',
    authDomain: 'adot-batimento.firebaseapp.com',
    databaseURL: 'https://adot-batimento-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adot-batimento.firebasestorage.app',
  );
}
